# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e39a4bc48c604176716fb49cdeebd046"
organization_id = "53792445"
name = "Product Card modification"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Complete permission set for discount management
scopes = "write_products,read_products,write_discounts,read_discounts,write_price_rules,read_price_rules,write_customers,read_customers,write_orders,read_orders"

[auth]
redirect_urls = [ 
  "https://example.com/api/auth"
]
