name = "checkout-discount"
type = "checkout_ui_extension"

[[extensions]]
type = "checkout_ui_extension"
name = "checkout-discount-monitor"
handle = "checkout-discount-monitor"

[extensions.targeting]
targets = [
  "purchase.checkout.delivery-address.render-after",
  "purchase.checkout.payment-method.render-after",
  "purchase.checkout.shipping-option.render-after"
]

[extensions.capabilities]
block_progress = false
network_access = true
api_access = true

[extensions.settings]
[[extensions.settings.fields]]
key = "enable_discount_monitoring"
type = "boolean"
name = "Enable Discount Monitoring"
description = "Monitor and verify discount calculations at checkout"
default = true

[[extensions.settings.fields]]
key = "show_discount_details"
type = "boolean" 
name = "Show Discount Details"
description = "Display detailed discount information to customers"
default = true 