name = "checkout-discount"
api_version = "2024-07"

[[extensions]]

uid = "24a4e01b-0feb-dfed-8250-f743d27dae98157c6842"

type = "ui_extension"
name = "checkout-discount-monitor"
handle = "checkout-discount-monitor"

[[extensions.targeting]]
target = "purchase.checkout.cart-line-list.render-after"
module = "./src/Checkout.jsx"

[extensions.capabilities]
network_access = true
api_access = true
block_progress = false 